trigger:
- main

variables:
  agentPoolName:  'local-azure-devops-agent'

pool:
  name: $(agentPoolName)

stages:
  - stage: Terraform Validate
    jobs:
      - job: TerraformValidateJob
        continueOnError: false
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Artifacts
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/terraform-code'
              artifact: 'terraform-manifests-out'
              publishLocation: 'pipeline'
          - task: TerraformInstaller@1
            displayName: Terraform Install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-code'
              backendServiceArm: 'Free Trial(4d909174-d9a2-424b-adc9-f78c9dcefb96)'
              backendAzureRmResourceGroupName: 'terraform-storage-for-tfstate'
              backendAzureRmStorageAccountName: 'tfstateremotebackup'
              backendAzureRmContainerName: 'tfstatefiles'
              backendAzureRmKey: 'aks-azure-devops.tfstate'
          - task: TerraformTaskV4@4
            displayName: Terraform Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-code'
          